#!/bin/bash


# Installing the gcloud CLI
setup_gcloud() {
    sudo apt-get update
    sudo apt-get install apt-transport-https ca-certificates gnupg curl
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    sudo apt-get update && sudo apt-get install google-cloud-cli

    # Authorize with a user account
    gcloud init

    # Authorize a service account using service account impersonation
    # 1. Authorize the gcloud CLI with your user identity
    # gcloud init
    # 2. Set up the gcloud CLI to use the identity and access provided by a service account by default
    # gcloud config set auth/impersonate_service_account SERVICE_ACCT_EMAIL

    # Authorize a service account using a service account key
    # gcloud auth login --cred-file=KEY_FILE
}


# Installing Python
setup_python() {
    sudo apt update
    sudo apt install python3 python3-dev python3-venv
    sudo apt-get install wget
    wget https://bootstrap.pypa.io/get-pip.py
    sudo python3 get-pip.py
    pip3 --version # (optional)

    # Using venv to isolate dependencies
    python3 -m venv env
    source env/bin/activate

    # Installing the Cloud Client Libraries for Python
    pip install google-cloud-storage
}


setup_gcloud
setup_python
