#!/bin/bash


export SERVICE_ACCT_EMAIL='clouduploader-storage-admin@sodium-hue-427709-u4.iam.gserviceaccount.com'


# Installing the gcloud CLI
setup_gcloud() {
    sudo apt-get update
    sudo apt-get install apt-transport-https ca-certificates gnupg curl
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    sudo apt-get update && sudo apt-get install google-cloud-cli
    
    # Set up authentication
    if [ -z $SERVICE_ACCT_EMAIL ]; then
        gcloud auth application-default login --impersonate-service-account $SERVICE_ACCT_EMAIL
    else
        gcloud auth application-default login
    fi
}


setup_python() {
    # Installing Python
    sudo apt update
    sudo apt install python3 python3-dev python3-venv
    sudo apt-get install wget
    wget https://bootstrap.pypa.io/get-pip.py
    sudo python3 get-pip.py
    pip3 --version # (optional)

    # Using venv to isolate dependencies
    python3 -m venv env
    source env/bin/activate

    # Installing the Cloud Client Libraries for Python
    pip install google-cloud-storage
}


setup_gcloud
setup_python